"""Default-off C04 legacy tail/effect mapping without side effects.

The C03 backfill plan proves only how each legacy record must be handled.  C04
adds a deterministic *would-run* map for future outbox, object-reference and
Provider work.  It accepts hash-only tail descriptors and returns hash-only
stable keys and gaps.  It does not write an outbox row, object reference,
Provider effect, callback receipt, or Owner Truth target.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from hashlib import sha256
import json
import re
from typing import Dict, Iterable, Mapping, Optional, Sequence, Tuple
from uuid import UUID

from app.async_effects.contracts import AsyncEffectIntent, AsyncEffectTarget
from app.async_effects.provider_effects import (
    ProviderEffectCatalogEntry,
    ProviderEffectIntent,
    provider_effect_catalog,
)
from app.domain.owner_truth.legacy_backfill import (
    LegacyBackfillAdmissionAction,
    LegacyBackfillAdmissionPlan,
    LegacyBackfillAdmissionPlanEntry,
    OwnerTruthLegacyBackfillPlanError,
)
from app.domain.owner_truth.legacy_migration import LegacyMigrationDomain


OWNER_TRUTH_LEGACY_TAIL_SHADOW_SCHEMA_VERSION = "owner-truth-legacy-tail-shadow-v1"
_IDENTIFIER_PATTERN = re.compile(r"^[A-Za-z][A-Za-z0-9_.:-]{0,127}$")
_SHA256_PATTERN = re.compile(r"^[0-9a-f]{64}$")
_TAIL_ELIGIBLE_ACTIONS = frozenset(
    {
        LegacyBackfillAdmissionAction.REQUIRE_INDEPENDENT_LINEAGE_REPLAY,
        LegacyBackfillAdmissionAction.REQUIRE_OWNER_CANDIDATE_REVIEW,
        LegacyBackfillAdmissionAction.REQUIRE_EVIDENCE_REVIEW,
    }
)
_PURPOSE_BY_ACTION = {
    LegacyBackfillAdmissionAction.REQUIRE_INDEPENDENT_LINEAGE_REPLAY: "legacyIndependentLineageReplay",
    LegacyBackfillAdmissionAction.REQUIRE_OWNER_CANDIDATE_REVIEW: "legacyCandidateReview",
    LegacyBackfillAdmissionAction.REQUIRE_EVIDENCE_REVIEW: "legacyEvidenceReview",
}


class OwnerTruthLegacyTailShadowError(OwnerTruthLegacyBackfillPlanError):
    """A C04 shadow descriptor would be ambiguous or side-effectful."""


class OwnerTruthLegacyTailShadowConflict(OwnerTruthLegacyTailShadowError):
    """The same immutable legacy tail identity was rebound to new meaning."""


class LegacyTailShadowChannel(str, Enum):
    OUTBOX_JOB = "outboxJob"
    OBJECT_REFERENCE = "objectReference"
    PROVIDER_EFFECT = "providerEffect"


def _identifier(value: object, *, field: str) -> str:
    normalized = str(value or "").strip()
    if not _IDENTIFIER_PATTERN.fullmatch(normalized):
        raise OwnerTruthLegacyTailShadowError(f"{field} must be an opaque identifier")
    return normalized


def _sha256(value: object, *, field: str) -> str:
    normalized = str(value or "").strip().lower()
    if not _SHA256_PATTERN.fullmatch(normalized):
        raise OwnerTruthLegacyTailShadowError(f"{field} must be a lowercase SHA-256 digest")
    return normalized


def _uuid(value: object, *, field: str) -> str:
    normalized = str(value or "").strip()
    try:
        return str(UUID(normalized))
    except (TypeError, ValueError, AttributeError) as exc:
        raise OwnerTruthLegacyTailShadowError(f"{field} must be a UUID") from exc


def _non_negative_int(value: object, *, field: str) -> int:
    if isinstance(value, bool) or not isinstance(value, int) or value < 0:
        raise OwnerTruthLegacyTailShadowError(f"{field} must be a non-negative integer")
    return value


def _canonical_json(value: object) -> str:
    try:
        return json.dumps(value, ensure_ascii=True, sort_keys=True, separators=(",", ":"))
    except (TypeError, ValueError) as exc:
        raise OwnerTruthLegacyTailShadowError("legacy tail shadow material must be serializable") from exc


def _digest(value: object) -> str:
    return sha256(_canonical_json(value).encode("utf-8")).hexdigest()


@dataclass(frozen=True)
class LegacyTailShadowOperation:
    """One hash-only legacy tail event mapped to a future execution plane.

    ``tail_cursor_hash`` is a HMAC/hash generated by a trusted collector.  It
    is deliberately not a database cursor, primary key, timestamp or payload.
    """

    channel: LegacyTailShadowChannel
    domain: LegacyMigrationDomain
    legacy_id_hash: str
    record_hash: str
    tail_cursor_hash: str
    source_version: int
    object_reference_hash: Optional[str] = None
    provider_catalog_key: Optional[str] = None
    callback_fixture_hash: Optional[str] = None

    def __post_init__(self) -> None:
        object.__setattr__(self, "channel", LegacyTailShadowChannel(self.channel))
        object.__setattr__(self, "domain", LegacyMigrationDomain(self.domain))
        for field in ("legacy_id_hash", "record_hash", "tail_cursor_hash"):
            object.__setattr__(self, field, _sha256(getattr(self, field), field=field))
        object.__setattr__(
            self,
            "source_version",
            _non_negative_int(self.source_version, field="source_version"),
        )
        if self.object_reference_hash is not None:
            object.__setattr__(
                self,
                "object_reference_hash",
                _sha256(self.object_reference_hash, field="object_reference_hash"),
            )
        if self.provider_catalog_key is not None:
            object.__setattr__(
                self,
                "provider_catalog_key",
                _identifier(self.provider_catalog_key, field="provider_catalog_key"),
            )
        if self.callback_fixture_hash is not None:
            object.__setattr__(
                self,
                "callback_fixture_hash",
                _sha256(self.callback_fixture_hash, field="callback_fixture_hash"),
            )
        if self.channel is LegacyTailShadowChannel.OUTBOX_JOB:
            if any(
                value is not None
                for value in (
                    self.object_reference_hash,
                    self.provider_catalog_key,
                    self.callback_fixture_hash,
                )
            ):
                raise OwnerTruthLegacyTailShadowError(
                    "outboxJob mapping cannot carry object or Provider material"
                )
        elif self.channel is LegacyTailShadowChannel.OBJECT_REFERENCE:
            if self.object_reference_hash is None:
                raise OwnerTruthLegacyTailShadowError(
                    "objectReference mapping requires object_reference_hash"
                )
            if self.provider_catalog_key is not None or self.callback_fixture_hash is not None:
                raise OwnerTruthLegacyTailShadowError(
                    "objectReference mapping cannot carry Provider material"
                )
        elif self.channel is LegacyTailShadowChannel.PROVIDER_EFFECT:
            if self.provider_catalog_key is None or self.callback_fixture_hash is None:
                raise OwnerTruthLegacyTailShadowError(
                    "providerEffect mapping requires catalog and callback fixture hashes"
                )
            if self.object_reference_hash is not None:
                raise OwnerTruthLegacyTailShadowError(
                    "providerEffect mapping cannot carry object reference material"
                )

    @property
    def semantic_key(self) -> tuple[str, str, str, str]:
        discriminator = ""
        if self.channel is LegacyTailShadowChannel.OBJECT_REFERENCE:
            discriminator = self.object_reference_hash or ""
        elif self.channel is LegacyTailShadowChannel.PROVIDER_EFFECT:
            discriminator = self.provider_catalog_key or ""
        return (
            self.domain.value,
            self.legacy_id_hash,
            self.channel.value,
            discriminator,
        )

    @property
    def immutable_fingerprint(self) -> str:
        return _digest(
            {
                "callbackFixtureHash": self.callback_fixture_hash,
                "channel": self.channel.value,
                "domain": self.domain.value,
                "legacyIdHash": self.legacy_id_hash,
                "objectReferenceHash": self.object_reference_hash,
                "providerCatalogKey": self.provider_catalog_key,
                "recordHash": self.record_hash,
                "sourceVersion": self.source_version,
                "tailCursorHash": self.tail_cursor_hash,
            }
        )


@dataclass(frozen=True)
class LegacyTailShadowMapping:
    """A planned, non-persisted mapping with no execution capability."""

    channel: LegacyTailShadowChannel
    source_domain: LegacyMigrationDomain
    source_legacy_id_hash: str
    source_record_hash: str
    action: LegacyBackfillAdmissionAction
    operation_stable_key: str
    mapping_hash: str
    provider_catalog_key: Optional[str] = None
    provider_query_reconcile_support: Optional[str] = None
    object_reference_hash: Optional[str] = None
    callback_fixture_hash: Optional[str] = None

    def __post_init__(self) -> None:
        object.__setattr__(self, "channel", LegacyTailShadowChannel(self.channel))
        object.__setattr__(self, "source_domain", LegacyMigrationDomain(self.source_domain))
        object.__setattr__(
            self,
            "action",
            LegacyBackfillAdmissionAction(self.action),
        )
        for field in (
            "source_legacy_id_hash",
            "source_record_hash",
            "operation_stable_key",
            "mapping_hash",
        ):
            object.__setattr__(self, field, _sha256(getattr(self, field), field=field))
        if self.provider_catalog_key is not None:
            object.__setattr__(
                self,
                "provider_catalog_key",
                _identifier(self.provider_catalog_key, field="provider_catalog_key"),
            )
        if self.provider_query_reconcile_support is not None:
            object.__setattr__(
                self,
                "provider_query_reconcile_support",
                _identifier(
                    self.provider_query_reconcile_support,
                    field="provider_query_reconcile_support",
                ),
            )
        if self.object_reference_hash is not None:
            object.__setattr__(
                self,
                "object_reference_hash",
                _sha256(self.object_reference_hash, field="object_reference_hash"),
            )
        if self.callback_fixture_hash is not None:
            object.__setattr__(
                self,
                "callback_fixture_hash",
                _sha256(self.callback_fixture_hash, field="callback_fixture_hash"),
            )

    def summary(self) -> dict[str, object]:
        """QA-safe mapping summary; no source identifier or request body."""

        result: dict[str, object] = {
            "action": self.action.value,
            "channel": self.channel.value,
            "mappingHash": self.mapping_hash,
            "operationStableKey": self.operation_stable_key,
            "sourceDomain": self.source_domain.value,
        }
        if self.provider_catalog_key is not None:
            result["providerCatalogKey"] = self.provider_catalog_key
        if self.provider_query_reconcile_support is not None:
            result["providerQueryReconcileSupport"] = self.provider_query_reconcile_support
        if self.object_reference_hash is not None:
            result["objectReferenceHash"] = self.object_reference_hash
        if self.callback_fixture_hash is not None:
            result["callbackFixtureHash"] = self.callback_fixture_hash
        return result


@dataclass(frozen=True)
class LegacyTailShadowReport:
    """Deterministic C04 report that proves all real side effects remain zero."""

    plan_id: str
    plan_hash: str
    authority_epoch: int
    mappings: tuple[LegacyTailShadowMapping, ...]
    input_operation_count: int
    duplicate_input_count: int
    required_outbox_entry_count: int
    missing_outbox_mapping_count: int
    archive_object_evidence_gap_count: int
    unmapped_provider_catalog_keys: tuple[str, ...]
    tail_checkpoint_hash: str
    report_hash: str

    def __post_init__(self) -> None:
        object.__setattr__(self, "plan_id", _uuid(self.plan_id, field="plan_id"))
        object.__setattr__(self, "plan_hash", _sha256(self.plan_hash, field="plan_hash"))
        object.__setattr__(
            self,
            "authority_epoch",
            _non_negative_int(self.authority_epoch, field="authority_epoch"),
        )
        normalized_mappings = tuple(
            sorted(
                (LegacyTailShadowMapping(**mapping.__dict__) for mapping in self.mappings),
                key=lambda item: (item.channel.value, item.mapping_hash),
            )
        )
        if len({mapping.mapping_hash for mapping in normalized_mappings}) != len(normalized_mappings):
            raise OwnerTruthLegacyTailShadowError("tail shadow mappings must be unique")
        object.__setattr__(self, "mappings", normalized_mappings)
        for field in (
            "input_operation_count",
            "duplicate_input_count",
            "required_outbox_entry_count",
            "missing_outbox_mapping_count",
            "archive_object_evidence_gap_count",
        ):
            object.__setattr__(self, field, _non_negative_int(getattr(self, field), field=field))
        if self.input_operation_count != len(normalized_mappings) + self.duplicate_input_count:
            raise OwnerTruthLegacyTailShadowError(
                "input operation count must equal mappings plus exact duplicates"
            )
        if self.missing_outbox_mapping_count > self.required_outbox_entry_count:
            raise OwnerTruthLegacyTailShadowError("missing outbox mappings exceed required entries")
        catalog_keys = tuple(sorted({_identifier(key, field="provider_catalog_key") for key in self.unmapped_provider_catalog_keys}))
        object.__setattr__(self, "unmapped_provider_catalog_keys", catalog_keys)
        object.__setattr__(
            self,
            "tail_checkpoint_hash",
            _sha256(self.tail_checkpoint_hash, field="tail_checkpoint_hash"),
        )
        object.__setattr__(self, "report_hash", _sha256(self.report_hash, field="report_hash"))
        if self.tail_checkpoint_hash != _tail_checkpoint_hash(
            plan_hash=self.plan_hash,
            mappings=normalized_mappings,
        ):
            raise OwnerTruthLegacyTailShadowError("tail checkpoint hash is invalid")
        if self.report_hash != _report_hash(
            plan_id=self.plan_id,
            plan_hash=self.plan_hash,
            authority_epoch=self.authority_epoch,
            mappings=normalized_mappings,
            input_operation_count=self.input_operation_count,
            duplicate_input_count=self.duplicate_input_count,
            required_outbox_entry_count=self.required_outbox_entry_count,
            missing_outbox_mapping_count=self.missing_outbox_mapping_count,
            archive_object_evidence_gap_count=self.archive_object_evidence_gap_count,
            unmapped_provider_catalog_keys=catalog_keys,
            tail_checkpoint_hash=self.tail_checkpoint_hash,
        ):
            raise OwnerTruthLegacyTailShadowError("tail shadow report hash is invalid")

    @property
    def mapping_counts(self) -> dict[str, int]:
        counts: Dict[str, int] = {}
        for mapping in self.mappings:
            counts[mapping.channel.value] = counts.get(mapping.channel.value, 0) + 1
        return dict(sorted(counts.items()))

    @property
    def gap_count(self) -> int:
        return (
            self.missing_outbox_mapping_count
            + self.archive_object_evidence_gap_count
            + len(self.unmapped_provider_catalog_keys)
        )

    @property
    def ready_for_next_gate(self) -> bool:
        return self.gap_count == 0

    def value_free_summary(self) -> dict[str, object]:
        """Return an exportable C04 report without raw tail/object/provider data."""

        return {
            "archiveObjectEvidenceGapCount": self.archive_object_evidence_gap_count,
            "authorityEpoch": self.authority_epoch,
            "callbackAcceptedCount": 0,
            "cutoverAllowed": False,
            "duplicateInputCount": self.duplicate_input_count,
            "effectExecutionCount": 0,
            "gapCount": self.gap_count,
            "inputOperationCount": self.input_operation_count,
            "jobWriteCount": 0,
            "legacyWriterRetired": False,
            "mappingCount": len(self.mappings),
            "mappingCounts": self.mapping_counts,
            "mappings": [mapping.summary() for mapping in self.mappings],
            "missingOutboxMappingCount": self.missing_outbox_mapping_count,
            "objectStorageOperationCount": 0,
            "outboxWriteCount": 0,
            "planHash": self.plan_hash,
            "planId": self.plan_id,
            "providerCallCount": 0,
            "providerCallbackProcessedCount": 0,
            "readyForNextGate": self.ready_for_next_gate,
            "reportHash": self.report_hash,
            "requiredOutboxEntryCount": self.required_outbox_entry_count,
            "schemaVersion": OWNER_TRUTH_LEGACY_TAIL_SHADOW_SCHEMA_VERSION,
            "shadowOnly": True,
            "tailCheckpointHash": self.tail_checkpoint_hash,
            "unmappedProviderCatalogKeys": list(self.unmapped_provider_catalog_keys),
        }


def _entry_key(entry: LegacyBackfillAdmissionPlanEntry) -> tuple[str, str]:
    return (entry.domain.value, entry.legacy_id_hash)


def _operation_type(*, entry: LegacyBackfillAdmissionPlanEntry, channel: LegacyTailShadowChannel) -> str:
    return f"legacyMigration.{entry.domain.value}.{channel.value}"


def _effect_intent(
    *,
    plan: LegacyBackfillAdmissionPlan,
    entry: LegacyBackfillAdmissionPlanEntry,
    operation: LegacyTailShadowOperation,
) -> AsyncEffectIntent:
    purpose = _PURPOSE_BY_ACTION.get(entry.action)
    if purpose is None:
        raise OwnerTruthLegacyTailShadowError("non-admitting action cannot map to a tail effect")
    payload_hash = _digest(
        {
            "channel": operation.channel.value,
            "entry": entry.summary(),
            "planHash": plan.plan_hash,
            "sourceVersion": operation.source_version,
            "tailCursorHash": operation.tail_cursor_hash,
        }
    )
    return AsyncEffectIntent(
        operation_type=_operation_type(entry=entry, channel=operation.channel),
        target=AsyncEffectTarget(
            owner_subject_id=plan.owner_subject_id,
            vault_id=plan.vault_id,
            resource_type="legacyMigrationEntry",
            resource_id=entry.legacy_id_hash,
            resource_version=operation.source_version,
            purpose=purpose,
            authority_epoch=plan.authority_epoch,
        ),
        payload_hash=payload_hash,
    )


def _catalog_by_key(
    entries: Iterable[ProviderEffectCatalogEntry],
) -> dict[str, ProviderEffectCatalogEntry]:
    catalog = tuple(entries)
    if any(not isinstance(entry, ProviderEffectCatalogEntry) for entry in catalog):
        raise OwnerTruthLegacyTailShadowError(
            "Provider effect catalog must contain ProviderEffectCatalogEntry values"
        )
    result = {entry.key: entry for entry in catalog}
    if len(result) != len(catalog):
        raise OwnerTruthLegacyTailShadowError("Provider effect catalog keys must be unique")
    return result


def _mapping_for_operation(
    *,
    plan: LegacyBackfillAdmissionPlan,
    entry: LegacyBackfillAdmissionPlanEntry,
    operation: LegacyTailShadowOperation,
    catalog: Mapping[str, ProviderEffectCatalogEntry],
) -> LegacyTailShadowMapping:
    effect_intent = _effect_intent(plan=plan, entry=entry, operation=operation)
    provider_catalog_key: Optional[str] = None
    provider_query_reconcile_support: Optional[str] = None
    object_reference_hash: Optional[str] = None
    callback_fixture_hash: Optional[str] = None
    operation_stable_key = effect_intent.stable_key
    if operation.channel is LegacyTailShadowChannel.OBJECT_REFERENCE:
        object_reference_hash = operation.object_reference_hash
        assert object_reference_hash is not None
        operation_stable_key = _digest(
            {
                "effectStableKey": effect_intent.stable_key,
                "objectReferenceHash": object_reference_hash,
                "planHash": plan.plan_hash,
            }
        )
    elif operation.channel is LegacyTailShadowChannel.PROVIDER_EFFECT:
        provider_catalog_key = operation.provider_catalog_key
        callback_fixture_hash = operation.callback_fixture_hash
        assert provider_catalog_key is not None and callback_fixture_hash is not None
        catalog_entry = catalog.get(provider_catalog_key)
        if catalog_entry is None:
            raise OwnerTruthLegacyTailShadowError("providerEffect mapping references an unknown catalog key")
        if not catalog_entry.requires_stable_provider_effect:
            raise OwnerTruthLegacyTailShadowError(
                "providerEffect mapping cannot promote a read-only catalog entry"
            )
        provider_intent = ProviderEffectIntent(
            effect_intent=effect_intent,
            provider=catalog_entry.provider,
            capability=catalog_entry.capability,
            request_hash=_digest(
                {
                    "callbackFixtureHash": callback_fixture_hash,
                    "planHash": plan.plan_hash,
                    "sourceRecordHash": entry.record_hash,
                    "tailCursorHash": operation.tail_cursor_hash,
                }
            ),
        )
        operation_stable_key = provider_intent.provider_effect_key
        provider_query_reconcile_support = catalog_entry.query_reconcile_support
    mapping_hash = _digest(
        {
            "action": entry.action.value,
            "callbackFixtureHash": callback_fixture_hash,
            "channel": operation.channel.value,
            "objectReferenceHash": object_reference_hash,
            "operationStableKey": operation_stable_key,
            "planHash": plan.plan_hash,
            "providerCatalogKey": provider_catalog_key,
            "providerQueryReconcileSupport": provider_query_reconcile_support,
            "recordHash": entry.record_hash,
            "sourceDomain": entry.domain.value,
            "sourceLegacyIdHash": entry.legacy_id_hash,
        }
    )
    return LegacyTailShadowMapping(
        channel=operation.channel,
        source_domain=entry.domain,
        source_legacy_id_hash=entry.legacy_id_hash,
        source_record_hash=entry.record_hash,
        action=entry.action,
        operation_stable_key=operation_stable_key,
        mapping_hash=mapping_hash,
        provider_catalog_key=provider_catalog_key,
        provider_query_reconcile_support=provider_query_reconcile_support,
        object_reference_hash=object_reference_hash,
        callback_fixture_hash=callback_fixture_hash,
    )


def _tail_checkpoint_hash(
    *,
    plan_hash: str,
    mappings: Sequence[LegacyTailShadowMapping],
) -> str:
    return _digest(
        {
            "mappings": [mapping.summary() for mapping in mappings],
            "planHash": plan_hash,
            "schemaVersion": OWNER_TRUTH_LEGACY_TAIL_SHADOW_SCHEMA_VERSION,
        }
    )


def _report_hash(
    *,
    plan_id: str,
    plan_hash: str,
    authority_epoch: int,
    mappings: Sequence[LegacyTailShadowMapping],
    input_operation_count: int,
    duplicate_input_count: int,
    required_outbox_entry_count: int,
    missing_outbox_mapping_count: int,
    archive_object_evidence_gap_count: int,
    unmapped_provider_catalog_keys: Sequence[str],
    tail_checkpoint_hash: str,
) -> str:
    return _digest(
        {
            "archiveObjectEvidenceGapCount": archive_object_evidence_gap_count,
            "authorityEpoch": authority_epoch,
            "duplicateInputCount": duplicate_input_count,
            "inputOperationCount": input_operation_count,
            "mappings": [mapping.summary() for mapping in mappings],
            "missingOutboxMappingCount": missing_outbox_mapping_count,
            "planHash": plan_hash,
            "planId": plan_id,
            "requiredOutboxEntryCount": required_outbox_entry_count,
            "schemaVersion": OWNER_TRUTH_LEGACY_TAIL_SHADOW_SCHEMA_VERSION,
            "tailCheckpointHash": tail_checkpoint_hash,
            "unmappedProviderCatalogKeys": list(unmapped_provider_catalog_keys),
        }
    )


def build_legacy_tail_shadow_report(
    *,
    plan: LegacyBackfillAdmissionPlan,
    operations: Iterable[LegacyTailShadowOperation],
    catalog_entries: Optional[Iterable[ProviderEffectCatalogEntry]] = None,
) -> LegacyTailShadowReport:
    """Map C03 entries to would-run planes while preserving a hard no-effect boundary.

    The returned report deliberately records missing mappings as gaps. It never
    attempts to compensate by writing an async operation, uploading/copying an
    object, or invoking/querying a Provider.
    """

    if not isinstance(plan, LegacyBackfillAdmissionPlan):
        raise OwnerTruthLegacyTailShadowError("legacy backfill plan is required")
    normalized_operations = tuple(operations)
    if any(not isinstance(operation, LegacyTailShadowOperation) for operation in normalized_operations):
        raise OwnerTruthLegacyTailShadowError("operations must contain LegacyTailShadowOperation")
    catalog = _catalog_by_key(provider_effect_catalog() if catalog_entries is None else catalog_entries)
    plan_entries = {_entry_key(entry): entry for entry in plan.entries}
    unique_operations: Dict[tuple[str, str, str, str], LegacyTailShadowOperation] = {}
    duplicate_input_count = 0
    for operation in normalized_operations:
        entry = plan_entries.get((operation.domain.value, operation.legacy_id_hash))
        if entry is None or entry.record_hash != operation.record_hash:
            raise OwnerTruthLegacyTailShadowError(
                "tail operation does not match the immutable legacy admission plan"
            )
        if entry.action not in _TAIL_ELIGIBLE_ACTIONS:
            raise OwnerTruthLegacyTailShadowError(
                "quarantined or excluded legacy entry cannot produce a tail operation"
            )
        existing = unique_operations.get(operation.semantic_key)
        if existing is None:
            unique_operations[operation.semantic_key] = operation
        elif existing.immutable_fingerprint == operation.immutable_fingerprint:
            duplicate_input_count += 1
        else:
            raise OwnerTruthLegacyTailShadowConflict(
                "legacy tail operation identity was rebound to different immutable input"
            )
    mappings = tuple(
        sorted(
            (
                _mapping_for_operation(
                    plan=plan,
                    entry=plan_entries[(operation.domain.value, operation.legacy_id_hash)],
                    operation=operation,
                    catalog=catalog,
                )
                for operation in unique_operations.values()
            ),
            key=lambda item: (item.channel.value, item.mapping_hash),
        )
    )
    required_outbox_entries = tuple(
        entry for entry in plan.entries if entry.action in _TAIL_ELIGIBLE_ACTIONS
    )
    mapped_outbox_entries = {
        (mapping.source_domain.value, mapping.source_legacy_id_hash)
        for mapping in mappings
        if mapping.channel is LegacyTailShadowChannel.OUTBOX_JOB
    }
    missing_outbox_mapping_count = sum(
        int(_entry_key(entry) not in mapped_outbox_entries) for entry in required_outbox_entries
    )
    archive_entries = tuple(
        entry
        for entry in required_outbox_entries
        if entry.domain is LegacyMigrationDomain.ARCHIVE_ITEM
    )
    mapped_archive_objects = {
        (mapping.source_domain.value, mapping.source_legacy_id_hash)
        for mapping in mappings
        if mapping.channel is LegacyTailShadowChannel.OBJECT_REFERENCE
    }
    archive_object_evidence_gap_count = sum(
        int(_entry_key(entry) not in mapped_archive_objects) for entry in archive_entries
    )
    required_provider_keys = {
        entry.key for entry in catalog.values() if entry.requires_stable_provider_effect
    }
    mapped_provider_keys = {
        mapping.provider_catalog_key
        for mapping in mappings
        if mapping.channel is LegacyTailShadowChannel.PROVIDER_EFFECT
        and mapping.provider_catalog_key is not None
    }
    unmapped_provider_catalog_keys = tuple(sorted(required_provider_keys - mapped_provider_keys))
    checkpoint = _tail_checkpoint_hash(plan_hash=plan.plan_hash, mappings=mappings)
    report_hash = _report_hash(
        plan_id=plan.plan_id,
        plan_hash=plan.plan_hash,
        authority_epoch=plan.authority_epoch,
        mappings=mappings,
        input_operation_count=len(normalized_operations),
        duplicate_input_count=duplicate_input_count,
        required_outbox_entry_count=len(required_outbox_entries),
        missing_outbox_mapping_count=missing_outbox_mapping_count,
        archive_object_evidence_gap_count=archive_object_evidence_gap_count,
        unmapped_provider_catalog_keys=unmapped_provider_catalog_keys,
        tail_checkpoint_hash=checkpoint,
    )
    return LegacyTailShadowReport(
        plan_id=plan.plan_id,
        plan_hash=plan.plan_hash,
        authority_epoch=plan.authority_epoch,
        mappings=mappings,
        input_operation_count=len(normalized_operations),
        duplicate_input_count=duplicate_input_count,
        required_outbox_entry_count=len(required_outbox_entries),
        missing_outbox_mapping_count=missing_outbox_mapping_count,
        archive_object_evidence_gap_count=archive_object_evidence_gap_count,
        unmapped_provider_catalog_keys=unmapped_provider_catalog_keys,
        tail_checkpoint_hash=checkpoint,
        report_hash=report_hash,
    )


__all__ = [
    "OWNER_TRUTH_LEGACY_TAIL_SHADOW_SCHEMA_VERSION",
    "LegacyTailShadowChannel",
    "LegacyTailShadowMapping",
    "LegacyTailShadowOperation",
    "LegacyTailShadowReport",
    "OwnerTruthLegacyTailShadowConflict",
    "OwnerTruthLegacyTailShadowError",
    "build_legacy_tail_shadow_report",
]
